config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # root 'home#index', as: 'home_index', via: :all
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
  resources :clients
  resources :items
  resources :invoices do
    resources :line_items, except: [:index]
    post :add_item, on: :collection
  end
  resources :after_register

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/regions', to: 'countries#regions'
  get '/dashboard', to: 'dashboard#index'
  get 'charts/show', as: :chart

  # scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
  #   resources :users
  #   resources :dashboard
  #   resources :invoices
  #   resources :clients
  #   resources :items
  # end

  # localized do
  #   resources :users
  #   # get '/users/edit', to: 'registrations#edit', as: :edit_user_registration
  #   get '/invoices', to: 'invoices#index', as: :invoices
  #   get '/invoices/new', to: 'invoices#new', as: :new_invoice
  #   get '/invoices/:id', to: 'invoices#show', as: :show_invoice
  #   get '/invoices/edit/:id', to: 'invoices#edit', as: :edit_invoice
  #   get '/clients', to: 'clients#index', as: :clients
  #   get '/clients/new', to: 'clients#new', as: :new_client
  #   get '/clients/:id', to: 'clients#show', as: :show_client
  #   get '/clients/edit/:id', to: 'clients#edit', as: :edit_client
  #   get '/items', to: 'items#index', as: :items
  #   get '/items/new', to: 'items#new', as: :new_item
  #   get '/items/:id', to: 'items#show', as: :show_item
  #   get '/items/edit/:id', to: 'items#edit', as: :edit_item
  #   get '/dashboard', to: 'dashboard#index', as: :dashboard
  #   get '/privacy', to: 'home#privacy', as: :privacy
  # end

  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
end

app/models/invoice.rb
# frozen_string_literal: true

# Invoice model including search with association
class Invoice < ApplicationRecord # rubocop:disable Metrics/ClassLength
  belongs_to :client
  belongs_to :user

  has_many :line_items, dependent: :destroy
  has_many :items, through: :line_items
  accepts_nested_attributes_for :line_items, allow_destroy: true

  validates :client_id, presence: true

  attribute :status, :string, default: 'pendiente'

  before_create :set_invoice_number

  scope :for_account, ->(user_id) { where(user_id:) }

  scope :filter_status, ->(status) { where(status:) }

  scope :due, -> { where('due_date <= ?', Date.today) }
  scope :about_to_be_due, -> { where('due_date = ?', Date.tomorrow) }

  pg_search_scope :search,
                  against: %i[invoice_number status notes],
                  associated_against: {
                    client: %i[first_name last_name]
                  },
                  using: { tsearch: { prefix: true } },
                  ignoring: :accents

  def client_full_name
    Client.find(client_id).full_name
  end

  def set_invoice_number
    last_invoice = Invoice.last
    self.invoice_number = if last_invoice.nil?
                            1
                          elsif Invoice.last.invoice_number.to_i
                            Invoice.last.invoice_number.to_i + 1
                          else
                            Invoice.last.invoice_number
                          end
  end

  def self.total_invoice_count
    count
  end

  def self.total_paid_count
    filter_status('pagada').count
  end

  def self.total_not_paid_count
    filter_status('pendiente').count
  end

  def self.total_due_count
    due.count
  end

  def self.total_about_to_be_due_count
    about_to_be_due.count
  end

  def sum_subtotal
    line_items.sum(&:sub_total)
  end

  def sum_total
    line_items.sum(&:total_price)
  end

  def sum_iva
    line_items.sum(&:total_iva)
  end

  def past_due?
    return 'past-due' if due_date.past?

    'on-time'
  end

  def status?
    return 'paid' if status == 'pagada'

    'not-paid' if status == 'pendiente'
  end

  def pdf_line_items
    the_line_items = []
    the_line_items << ['<b>' + I18n.t('item') + '</b>', '<b>' + I18n.t('cantidad') + '</b>', '<b>' + I18n.t('importe') + '</b>',
                       '<b>' + I18n.t('iva') + '</b>', '<b>' + I18n.t('monto') + '</b>']
    line_items.map do |l|
      line = [l.item.item_name, l.quantity, ActionController::Base.helpers.number_to_currency(l.item.price),
              l.item.iva, ActionController::Base.helpers.number_to_currency((l.item.price * l.quantity * (1 + l.item.iva / 100)))]
      the_line_items << line
    end
    the_line_items << [nil, nil, nil, I18n.t('subtotal'), ActionController::Base.helpers.number_to_currency(subtotal)]
    the_line_items << [nil, nil, nil, I18n.t('iva'), ActionController::Base.helpers.number_to_currency(iva)]
    the_line_items << [nil, nil, nil, 'TOTAL', ActionController::Base.helpers.number_to_currency(total)]
    the_line_items
  end

  def pdf
    client = Client.find(client_id)
    user = User.find(user_id)
    Receipts::Invoice.new(
      title: I18n.t('factura'),
      details: [
        [I18n.t('factura') + ' #', invoice_number],
        [I18n.t('fecha'), date.strftime('%B %d, %Y')],
        [I18n.t('fecha_vencimiento'), due_date.strftime('%B %d, %Y')],
        [I18n.t('estatus'), "<b><color rgb='#5eba7d'>#{status.upcase}</color></b>"]
      ],
      recipient: [
        I18n.t('facturado_a'),
        client.full_name,
        client.address_line1,
        client.address_line2,
        client.email
      ],
      company: {
        name: user.user_profile.full_name,
        address: user.user_profile.address_line1 + "\n" + user.user_profile.address_line_3,
        phone: user.user_profile.phone,
        email: user.user_profile.email,
        logo: File.expand_path('app/assets/images/logo.png')
      },
      line_items: pdf_line_items,
      footer: notes
    )
  end
end

app/controllers/invoices_controller.rb
# frozen_string_literal: true

# Invoice controller with search, sort, and filter
class InvoicesController < ApplicationController # rubocop:disable Metrics/ClassLength
  before_action :authenticate_user!
  before_action :set_invoice, only: %i[show edit update destroy]

  # GET /invoices or /invoices.json
  def index # rubocop:disable Metrics/AbcSize
    @invoices = current_user.invoices
    @invoices = current_user.invoices.filter_status(params[:status]) if params[:status].present?
    @invoices = current_user.invoices.search(params[:query]) if params[:query].present?
    @pagy, @invoices = pagy @invoices.reorder(sort_column => sort_direction), items: params.fetch(:count, 10)
  end

  def sort_column
    %w[invoice_number total status date due_date].include?(params[:sort]) ? params[:sort] : 'invoice_number'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  # GET /invoices/1 or /invoices/1.json
  def show
    @client = Client.find(@invoice.client_id).full_name
    respond_to do |format|
      format.html
      format.json
      format.pdf { send_pdf }
    end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.line_items.build
  end

  # GET /invoices/1/edit
  def edit
    @client = Client.find(@invoice.client_id)
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.user = current_user

    respond_to do |format|
      if @invoice.save
        format.html do
          redirect_to invoices_path, notice: I18n.t('factura_creada')
        end
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @invoice.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def add_item
    helpers.fields model: Invoice.new do |f|
      render turbo_stream: turbo_stream.append(
        'line_items',
        partial: 'item_fields',
        locals: { f:, line_item: LineItem.new, turboid: Process.clock_gettime(Process::CLOCK_REALTIME, :millisecond) }
      )
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html do
          redirect_to invoices_url,
                      notice: I18n.t('factura_editada')
        end
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @invoice.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html do
        redirect_to invoices_url, notice: I18n.t('factura_borrada')
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def invoice_params
    params.require(:invoice).permit(
      :client_id,
      :invoice_number,
      :date,
      :due_date,
      :subtotal,
      :iva,
      :irpf,
      :total,
      :notes,
      :status,
      line_items_attributes: %i[id item_id invoice_id quantity price iva total _destroy]
    )
  end

  def send_pdf
    # Render the PDF in memory and send as the response
    send_data @invoice.pdf.render,
              filename: "#{@invoice.created_at.strftime('%Y-%m-%d')}-invoice.pdf",
              type: 'application/pdf',
              disposition: :inline # or :attachment to download
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<div class="my-8 px-8 py-4 bg-white shadow-lg rounded-sm border border-slate-200" data-controller='toggle'>
  <%= form_with(model: invoice, class: "contents", html: { data: {controller: "recalculate"} } ) do |f| %>

    <h2 class="text-lg font-bold"><%= t("cabecera_factura") %></h2>

    <div class="grid grid-cols-5 gap-2" data-controller="clientselect" data-clientselect-url-value="<%= clients_path %>" data-clientselect-param-value="client">
      <div class="my-5 col-span-2 flex flex-col">
        <%= f.label t("cliente"), class: "input-label"  %>
        <div class="relative rounded-md shadow-sm">
          <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <%= heroicon "users", options: {class: "w-4 h-4 fill-current text-slate-400 shrink-0" } %>
          </div>
          <%= f.collection_select :client_id, current_user.clients.order(:first_name), :id, :full_name, {prompt: t("selecciona_cliente")}, {data: {action: "change->clientselect#change"}, class: "form-select w-full pl-10"} %>
        </div>
        <%= link_to new_client_path(id: f.object), class: "text-indigo-600 hover:underline mt-2", data: { turbo_method: :post } do %>
          <%= (heroicon "plus", options: { class: "inline -mt-1"} ) + t("agregar_nuevo_cliente") %>
        <% end %>
      </div>

      <div class="my-5">
        <%= f.label t("numero_factura"), class: "input-label"  %>
        <div class="relative mt-1 rounded-md shadow-sm">
          <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <%= heroicon "hashtag", options: {class: "w-4 h-4 fill-current text-slate-400 shrink-0" } %>
          </div>
          <% if invoice.new_record? %>
            <%= f.text_field :invoice_number, class: "form-input w-full pl-8", value: invoice.set_invoice_number %>
          <% else %>
            <%= f.text_field :invoice_number, class: "form-input w-full pl-8", value: invoice.invoice_number %>
          <% end %>
        </div>
      </div>

      <div class="my-5 col-span-1">
        <%= f.label t("fecha"), class: "input-label"  %>
        <%= f.date_field :date, class: "form-input w-full", value: (@invoice.date || Date.today)%>
      </div>

      <div class="my-5">
        <%= f.label t("fecha_vencimiento"), class: "input-label"  %>
        <%= f.date_field :due_date, class: "form-input w-full", value: (@invoice.due_date || Date.today + 30.days) %>
      </div>

      <div id="client_details" class="col-span-2" data-clientselect-target="select"></div>

    </div>

    <hr/>

    <h2 class="text-lg my-5 font-bold"><%= t "items_facturar" %></h2>

    <div id="line_items" class=" mb-6">
      <% f.object.line_items.each do |i| %>
        <%= render "item_fields", f: f, line_item: i, turboid: Process.clock_gettime(Process::CLOCK_REALTIME, :millisecond) %>
      <% end %>
    </div>

    <%= link_to add_item_invoices_path(id: f.object), class: "text-indigo-600 hover:underline",
      data: { turbo_method: :post } do %>
      <%= (heroicon "plus", options: { class: "inline -mt-1"} ) + t("agregar_linea_item") %>
    <% end %>

    <hr class="mt-5"/>

    <div class="flex justify-between items-center cursor-pointer" data-action='click->toggle#toggle touch->toggle#toggle'>
      <h2 class="flex text-lg my-5 font-bold"><%= t("mas_opciones") %></h2>
      <%= link_to "#", class: "text-indigo-600 hover:underline" do %>
        <%= (heroicon "chevron-up-down", options: { class: "inline"} ) %>
        <%= t("mostrar") %>
      <% end %>
    </div>
    <div class="hidden" data-toggle-target='toggleable'>
      <%= f.label t("notas"), class: "input-label"  %>
      <%= f.text_area :notes, rows: 6, maxlength: 700, class: "form-input w-full" %>
    </div>

    <hr class="mt-5"/>

    <div class="flex space-x-16">
      <div class="w-2/3 my-5">
        <span class="hidden">Payment Box</span>
      </div>

      <div id="<%= dom_id(@invoice, :total) %>" class="w-1/2 my-5">

        <%= render "total", f: f, invoice: @invoice%>

      </div>
    </div>

    <hr class="mb-5"/>

    <div class="inline">
      <%= f.submit t("guardar_factura"), class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/invoices/_invoice.html.erb
                    <tr >
                        <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap w-px">
                            <div class="flex items-center">
                                <label class="inline-flex">
                                    <span class="sr-only"><%= t("seleccionar") %></span>
                                    <input class="table-item form-checkbox" type="checkbox" @click="uncheckParent" />
                                </label>
                            </div>
                        </td>
                        <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                            <div class="font-medium text-sky-500">#<%= invoice.invoice_number %></div>
                        </td>
                        <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                            <div class="font-medium text-rose-500"><%= number_to_currency(invoice.total, locale: :es) %></div>
                        </td>
                        <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                            <div class="<%= invoice.status? %>"><%= t invoice.status.titleize %></div>
                        </td>
                        <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                            <div class="font-medium text-slate-800"><%= invoice.client_full_name %></div>
                        </td>
                        <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                            <div><%= l(invoice.date, format: :corta) %></div>
                        </td>
                        <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                            <div class="<%= invoice.past_due? %>"><%= l(invoice.due_date, format: :corta) %>
                            </div>
                        </td>
                        <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap w-px">
                            <div class="space-x-1 inline-flex">
                                <%= link_to edit_invoice_path(invoice), data: { turbo_frame: "_top" }, class: "text-slate-400 hover:text-slate-500" do %>
                                    <span class="sr-only"><%= t("editar") %></span>
                                    <svg class="w-8 h-8 fill-current" viewBox="0 0 32 32">
                                        <path d="M19.7 8.3c-.4-.4-1-.4-1.4 0l-10 10c-.2.2-.3.4-.3.7v4c0 .6.4 1 1 1h4c.3 0 .5-.1.7-.3l10-10c.4-.4.4-1 0-1.4l-4-4zM12.6 22H10v-2.6l6-6 2.6 2.6-6 6zm7.4-7.4L17.4 12l1.6-1.6 2.6 2.6-1.6 1.6z" />
                                    </svg>
                                <% end %>
                                <%= link_to invoice_path(invoice, format: :pdf, locale: I18n.locale), class: "text-slate-400 hover:text-slate-500", target: "_blank" do %>
                                    <span class="sr-only"><%= t("descargar") %></span>
                                    <svg class="w-8 h-8 fill-current" viewBox="0 0 32 32">
                                        <path d="M16 20c.3 0 .5-.1.7-.3l5.7-5.7-1.4-1.4-4 4V8h-2v8.6l-4-4L9.6 14l5.7 5.7c.2.2.4.3.7.3zM9 22h14v2H9z" />
                                    </svg>
                                <% end %>
                                <%= button_to invoice, method: :delete, form: { data: { turbo_confirm: t("estas_seguro") } }, class: "text-rose-500 hover:text-rose-600" do %>
                                    <span class="sr-only"><%= t("eliminar") %></span>
                                    <svg class="w-8 h-8 fill-current" viewBox="0 0 32 32">
                                        <path d="M13 15h2v6h-2zM17 15h2v6h-2z" />
                                        <path d="M20 9c0-.6-.4-1-1-1h-6c-.6 0-1 .4-1 1v2H8v2h1v10c0 .6.4 1 1 1h12c.6 0 1-.4 1-1V13h1v-2h-4V9zm-6 1h4v1h-4v-1zm7 3v9H11v-9h10z" />
                                    </svg>
                                <% end %>
                            </div>
                        </td>
                    </tr>
                  

app/views/invoices/_invoice.old.html.erb
<div id="<%= dom_id invoice %>">

  <p class="my-5">
    <strong class="block font-medium mb-1">Number:</strong>
    <%= invoice.invoice_number %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Date:</strong>
    <%= invoice.date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Due date:</strong>
    <%= invoice.due_date %>
  </p>

  <% if invoice.items.any? %>
    <%= render invoice.items %>
  <% end %>

  <p class="my-5">
    <strong class="block font-medium mb-1">Subtotal:</strong>
    <%= invoice.subtotal %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Iva:</strong>
    <%= invoice.iva %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Irpf:</strong>
    <%= invoice.irpf %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Total:</strong>
    <%= invoice.total %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Notes:</strong>
    <%= invoice.notes %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= invoice.status %>
  </p>

  <% if action_name != "show" %>
  <%= link_to "Show this invoice", invoice, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to 'Edit this invoice', edit_invoice_path(invoice), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
  <hr class="mt-6">
  <% end %>
</div>

app/views/invoices/_invoice_old.html.erb
<div id="<%= dom_id @invoice %>">

  <p class="my-5">
    <strong class="block font-medium mb-1">Client:</strong>
    <%= @client %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Number:</strong>
    <%= @invoice.invoice_number %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Date:</strong>
    <%= @invoice.date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Due date:</strong>
    <%= @invoice.due_date %>
  </p>

  <% if @invoice.items.any? %>
    <%= render @invoice.items %>
  <% end %>

  <p class="my-5">
    <strong class="block font-medium mb-1">Subtotal:</strong>
    <%= @invoice.subtotal %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Iva:</strong>
    <%= @invoice.iva %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Irpf:</strong>
    <%= @invoice.irpf %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Total:</strong>
    <%= @invoice.total %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Notes:</strong>
    <%= @invoice.notes %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= @invoice.status %>
  </p>

  <% if action_name != "show" %>
  <%= link_to "Show this invoice", invoice, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to 'Edit this invoice', edit_invoice_path(invoice), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
  <hr class="mt-6">
  <% end %>
</div>

app/views/invoices/_item_fields.html.erb
<div id="<%= turboid %>" 
  data-controller="removeitem" data-recalculate-target="theid" data-removeitem-target="item"
>
  <div class="flex gap-2" data-controller="itemselect" data-itemselect-url-value="<%= items_path %>" data-itemselect-param-value="item">
    <%= f.fields_for :line_items, line_item, child_index: turboid do |ff| %>
      <%= ff.hidden_field :_destroy, "data-removeitem-target" => "theHidden" %>
      <div class="w-2/3">
        <%= ff.label t("item"), class: "input-label"  %>
        <div class="relative mt-1 rounded-md shadow-sm">
          <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <%= heroicon "cursor-arrow-rays", options: {class: "w-6 h-6 fill-current text-slate-400 shrink-0" } %>
          </div>
          <%= ff.collection_select :item_id, current_user.items, :id, :item_name,
          {prompt: "Selecciona un item"}, { multiple: false, data: {action: "change->itemselect#change"}, class: "form-input w-full pl-10"} %>
        </div>
      </div>
      <div class="w-1/6">
        <%= ff.label t("cantidad"), class: "input-label"  %>
        <%= ff.number_field :quantity, min: 0, max: 10000000, step: 1, class: "form-input w-full", 
          data: {action: "change->recalculate#recalculate", removeitem_target: "qty", recalculate_target: "qty"} %>
      </div>
      <div class="w-1/3">
        <div class="flex gap-1 items-baseline">
          <%= ff.label t("importe"), class: "input-label"  %>
          <span id="currency" class="text-xs">(<%= I18n.t('number.currency.format.unit') %>)</span>
        </div>
        <%= ff.text_field :price, readonly: true, class: "form-input w-full", value: line_item.price, data: { recalculate_target: "price", itemselect_target: "select" } %>
      </div>
      <div class="w-1/12">
        <div class="flex gap-1 items-baseline">
          <%= ff.label t("iva"), class: "input-label uppercase text-center" %>
          <span id="currency" class="text-xs">(%)</span>
        </div>
        <%= ff.text_field :iva, readonly: true, class: "form-input w-full", value: number_with_precision(line_item.iva, precision: 0), data: { recalculate_target: "iva" } %>
      </div>
      <div class="w-1/3">
        <div class="flex gap-1 justify-end items-baseline">
          <%= ff.label t("total_item"), class: "input-label"  %>
          <span id="currency" class="text-xs">(<%= I18n.t('number.currency.format.unit') %>)</span>
        </div>
        <%= ff.text_field :total, readonly: true, class: "form-input w-full text-right", value: (line_item.total), data: { recalculate_target: "total" } %>
      </div>
      <a class="text-red-600 hover:underline mt-3 cursor-pointer remove-link"
        data-action="click->removeitem#click recalculate#recalculate">
        <%= heroicon "x-mark", options: { id: "x-mark" }%>
    <% end %>
      </a>
  </div>
</div>

app/views/invoices/_total.html.erb
<div class="table w-full mt-5">
  <div class="table-row-group">
    <div class="table-row">
      <div class="table-cell input-label text-left"><%= t("subtotal") %></div>
      <div class="table-cell text-right text-lg py-1" data-recalculate-target="subtotal">
        <%= number_to_currency invoice.subtotal %>
      </div>
      <%= f.hidden_field :subtotal, value: invoice.subtotal, data: { recalculate_target: "hiddensubtotal"} %>
    </div>
    <div class="table-row">
      <div class="table-cell input-label text-left"><%= t("iva") %></div>
      <div class="table-cellp-2 text-right py-1" data-recalculate-target="taxtotal">
        <%= number_to_currency invoice.iva %>
      </div>
      <%= f.hidden_field :iva, value: invoice.iva, data: { recalculate_target: "hiddentaxtotal"} %>
    </div>
    <div class="hidden">
      <div class="table-cell input-label text-left"><%= t("irpf") %></div>
      <div class="table-cell text-right py-1" data-recalculate-target="irpf">
        <%= number_to_currency invoice.irpf %>
      </div>
      <%= f.hidden_field :irpf, value: invoice.irpf, data: { recalculate_target: "hiddenirpf"}  %>
    </div>
    <div class="table-row">
      <div class="table-cell input-label text-left text-xl font-bold"><%= t("total") %></div>
      <div class="table-cell text-right text-xl font-bold py-5" data-recalculate-target="grandtotal">
        <%= number_to_currency invoice.total %>
      </div>
      <%= f.hidden_field :total, value: invoice.total, data: { recalculate_target: "hiddengrandtotal"}  %>
    </div>
  </div>
</div>

app/views/invoices/edit.html.erb
<div class="mx-auto w-full">
  <%= link_to sanitize(t("regresar_a_facturas")), invoices_path, class: "back-button" %>
  <h1 class="text-2xl md:text-3xl text-slate-800 font-bold mt-2"><%= t("editar_factura")%> ✨</h1>

  <%= render "form", invoice: @invoice %>
  
</div>

app/views/invoices/new.html.erb
<div class="mx-auto w-full">
    <%= link_to sanitize(t("regresar_a_facturas")), invoices_path, class: "back-button" %>
  <h1 class="title"><%= t("nueva_factura")%> ✨</h1>

  <%= render "form", invoice: @invoice %>

</div>

app/views/invoices/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render "invoice_old" %>

    <%= link_to 'Edit this invoice', edit_invoice_path(@invoice), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this invoice', invoice_path(@invoice), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to invoices', invoices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/invoices/update.turbo_stream.erb
<%= turbo_stream.replace "client_details", @client %>
<%= render_turbo_stream_flash_messages %>