config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # root 'home#index', as: 'home_index', via: :all
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
  resources :clients
  resources :items
  resources :invoices do
    resources :line_items, except: [:index]
    post :add_item, on: :collection
  end
  resources :after_register

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/regions', to: 'countries#regions'
  get '/dashboard', to: 'dashboard#index'
  get 'charts/show', as: :chart

  # scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
  #   resources :users
  #   resources :dashboard
  #   resources :invoices
  #   resources :clients
  #   resources :items
  # end

  # localized do
  #   resources :users
  #   # get '/users/edit', to: 'registrations#edit', as: :edit_user_registration
  #   get '/invoices', to: 'invoices#index', as: :invoices
  #   get '/invoices/new', to: 'invoices#new', as: :new_invoice
  #   get '/invoices/:id', to: 'invoices#show', as: :show_invoice
  #   get '/invoices/edit/:id', to: 'invoices#edit', as: :edit_invoice
  #   get '/clients', to: 'clients#index', as: :clients
  #   get '/clients/new', to: 'clients#new', as: :new_client
  #   get '/clients/:id', to: 'clients#show', as: :show_client
  #   get '/clients/edit/:id', to: 'clients#edit', as: :edit_client
  #   get '/items', to: 'items#index', as: :items
  #   get '/items/new', to: 'items#new', as: :new_item
  #   get '/items/:id', to: 'items#show', as: :show_item
  #   get '/items/edit/:id', to: 'items#edit', as: :edit_item
  #   get '/dashboard', to: 'dashboard#index', as: :dashboard
  #   get '/privacy', to: 'home#privacy', as: :privacy
  # end

  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
end

app/views/shared/_empty_state.html.erb
<div class="border-t border-slate-200">
    <div class="max-w-2xl m-auto my-16">

        <div class="text-center px-4">
            <div class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-t from-slate-200 to-slate-100 mb-4">
              <%= image_tag "icon-01.svg", class: "-rotate-45", alt: "Empty state image" %>
            </div>
            <h2 class="text-2xl text-slate-800 font-bold mb-2"><%= title %></h2>
            <div class="mb-6"><%= text %></div>
            <%= link_to the_link, class: "btn bg-indigo-500 hover:bg-indigo-600 text-white", data: { turbo_frame: "_top" } do %>
              <svg class="w-4 h-4 fill-current opacity-50 shrink-0" viewBox="0 0 16 16">
                  <path d="M15 7H9V1c0-.6-.4-1-1-1S7 .4 7 1v6H1c-.6 0-1 .4-1 1s.4 1 1 1h6v6c0 .6.4 1 1 1s1-.4 1-1V9h6c.6 0 1-.4 1-1s-.4-1-1-1z" />
              </svg>
              <span class="ml-2"><%= button_text %></span>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div x-show="open" x-data="{ open: true }" x-transition x-init="setTimeout(() => open = false, 3000)"
    class="fixed <%= position %> z-60 flex pointer-events-none">
      <div @click.outside="open = false" @keydown.escape.window="open = false"
        class="inline-flex min-w-80 px-4 py-2 rounded-sm text-sm border <%= flash_class(flash_type) %>">
          <div class="flex w-full justify-between items-start">
              <div class="flex">
                  <svg class="w-4 h-4 shrink-0 fill-current opacity-80 mt-[3px] mr-3" viewBox="0 0 16 16">
                      <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm0 12c-.6 0-1-.4-1-1s.4-1 1-1 1 .4 1 1-.4 1-1 1zm1-3H7V4h2v5z" />
                  </svg>
                  <div @click="open = false"><%= message %></div>
              </div>
              <button class="opacity-70 hover:opacity-80 ml-3 mt-[3px]" >
                  <div class="sr-only"><%= t("cerrar")%></div>
                  <svg class="w-4 h-4 fill-current">
                      <path d="M7.95 6.536l4.242-4.243a1 1 0 111.415 1.414L9.364 7.95l4.243 4.242a1 1 0 11-1.415 1.415L7.95 9.364l-4.243 4.243a1 1 0 01-1.414-1.415L6.536 7.95 2.293 3.707a1 1 0 011.414-1.414L7.95 6.536z" />
                  </svg>
              </button>
          </div>
      </div>
  </div>
  <!-- End -->
<% end %>

app/views/shared/_footer.html.erb
<div class="w-full h-auto px-2 pt-12 pb-4 text-sm lg:px-6">
  <div class="flex flex-col-reverse p-4 text-sm lg:flex-row lg:justify-between lg:p-0">
    <div class="flex items-center justify-center">
        <span>&copy; <%= Date.today.year %> Fact</span>
    </div>
    <div class="flex flex-wrap justify-center">
        <%= link_to "Terms", terms_path, class: "text-gray-700 no-underline block px-4 lg:my-0 my-2" %>
        <%= link_to "Privacy", privacy_path, class: "text-gray-700 no-underline block px-4 lg:my-0 my-2" %>
    </div>
  </div>
</div>

app/views/shared/_head.html.erb
    <title>Facturación iO</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>

    <%= combobox_style_tag %>

app/views/shared/_modal.html.erb
  <div class="modal opacity-0 pointer-events-none" tabindex="-1" 
      data-controller="modal" 
      data-action="turbo:frame-load->modal#open turbo:submit-end->modal#close keydown.esc->modal#close"
      data-modal-target="modal"
      x-data="{ invokeStimulusClose: function() { dispatchEvent(new CustomEvent('invokeStimulusClose')); } }"
  >
    <div class="modal-content" x-on:click.away="invokeStimulusClose()" x-ref="modal">
      <%= turbo_frame_tag "modal" %>
    </div>

  </div>

app/views/shared/_pagination.html.erb
    <% if @pagy.pages > 1 %>
        <div class="mt-8">
            <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                <div class="text-sm text-slate-500 text-center sm:text-left">
                    <%== pagy_info(@pagy, item_name: item_name.pluralize(@pagy.count)) %>
                </div>
                <%== pagy_nav(@pagy) %>
            </div>
        </div>
    <% end %>

app/views/shared/_search_not_found.html.erb
<div class="border-t border-slate-200">
    <div class="max-w-2xl m-auto my-16">

        <div class="text-center px-4">
            <div class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-t from-slate-200 to-slate-100 mb-4">
              <%= image_tag "404-illustration.svg", alt: t("imagen_busqueda") %>
            </div>
            <h2 class="text-2xl text-slate-800 font-bold mb-2"><%= t("no_encontrado") %></h2>
            <div class="mb-6"><%= t("no_encontrado_texto") %></div>
            <%= link_to the_link, class: "btn bg-indigo-500 hover:bg-indigo-600 text-white", data: { turbo_frame: "_top" } do %>
              <%= heroicon "arrow-uturn-left" %>
              <span class="ml-2"><%= t("limpiar_busqueda") %></span>
            <% end %>
        </div>
    </div>
</div>