config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # root 'home#index', as: 'home_index', via: :all
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
  resources :clients
  resources :items
  resources :invoices do
    resources :line_items, except: [:index]
    post :add_item, on: :collection
  end
  resources :after_register

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/regions', to: 'countries#regions'
  get '/dashboard', to: 'dashboard#index'
  get 'charts/show', as: :chart

  # scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
  #   resources :users
  #   resources :dashboard
  #   resources :invoices
  #   resources :clients
  #   resources :items
  # end

  # localized do
  #   resources :users
  #   # get '/users/edit', to: 'registrations#edit', as: :edit_user_registration
  #   get '/invoices', to: 'invoices#index', as: :invoices
  #   get '/invoices/new', to: 'invoices#new', as: :new_invoice
  #   get '/invoices/:id', to: 'invoices#show', as: :show_invoice
  #   get '/invoices/edit/:id', to: 'invoices#edit', as: :edit_invoice
  #   get '/clients', to: 'clients#index', as: :clients
  #   get '/clients/new', to: 'clients#new', as: :new_client
  #   get '/clients/:id', to: 'clients#show', as: :show_client
  #   get '/clients/edit/:id', to: 'clients#edit', as: :edit_client
  #   get '/items', to: 'items#index', as: :items
  #   get '/items/new', to: 'items#new', as: :new_item
  #   get '/items/:id', to: 'items#show', as: :show_item
  #   get '/items/edit/:id', to: 'items#edit', as: :edit_item
  #   get '/dashboard', to: 'dashboard#index', as: :dashboard
  #   get '/privacy', to: 'home#privacy', as: :privacy
  # end

  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord # rubocop:disable Style/Documentation
  belongs_to :user
  has_many :invoices

  validates :first_name,
            :last_name,
            :nif,
            :street,
            :city,
            :region,
            :postal_code,
            :country,
            presence: true

  validates :nif, uniqueness: true

  validates :street, length: { maximum: 70 }
  validates :first_name, :last_name, :city, :region, :country, length: { maximum: 50 }
  validates :nif, :postal_code, length: { maximum: 12 }

  pg_search_scope :search,
                  against: %i[first_name last_name nif city region country],
                  using: { tsearch: { prefix: true } },
                  ignoring: :accents

  def full_name
    [first_name, last_name].reject(&:blank?).collect(&:titleize).join(' ')
  end

  def address
    [street, city, postal_code, region, country].reject(&:blank?).collect(&:titleize).join(', ')
  end

  def address_line1
    [street].reject(&:blank?).collect(&:titleize).join(', ')
  end

  def address_line2
    [city, postal_code, region, country].reject(&:blank?).collect(&:titleize).join(', ')
  end

  def to_combobox_display
    full_name # or `title`, `to_s`, etc.
  end
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

# ClientsController handles CRUD operations for clients in the application.
# It requires authentication for all actions and ensures that each action
# operates on the client associated with the current user.
#
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: %i[show edit update destroy]

  # GET /clients or /clients.json
  def index
    @clients = current_user.clients.includes(:invoices)
    apply_search_query if params[:query].present?
    apply_pagination
  end

  def sort_column
    %w[first_name email nif].include?(params[:sort]) ? params[:sort] : 'first_name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  # GET /clients/1 or /clients/1.json
  def show
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit; end

  # POST /clients or /clients.json
  def create
    @client = build_client
    @client.user = current_user
    respond_to { |format| handle_response(format) }
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to { |format| handle_update_response(format) }
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html do
        redirect_to clients_url, notice: I18n.t('client_destroyed')
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  def apply_search_query
    @clients = @clients.search(params[:query])
  end

  def apply_pagination
    @pagy, @clients = pagy(@clients.reorder(sort_column => sort_direction), items: params.fetch(:count, 10))
  end

  def build_client
    Client.new(client_params)
  end

  def handle_response(format) # rubocop:disable Metrics/AbcSize
    if @client.save
      format.html { redirect_to clients_url, notice: I18n.t('client_created') }
      format.json { render :show, status: :created, location: @client }
      format.turbo_stream { flash.now[:success] = I18n.t('client_created') }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @client.errors, status: :unprocessable_entity }
    end
  end

  def handle_update_response(format) # rubocop:disable Metrics/AbcSize
    if @client.update(client_params)
      format.html { redirect_to clients_url, notice: I18n.t('client_updated') }
      format.json { render :show, status: :ok, location: @client }
      format.turbo_stream { flash.now[:success] = I18n.t('client_updated') }
    else
      format.html { render :edit, status: :unprocessable_entity }
      format.json { render json: @client.errors, status: :unprocessable_entity }
    end
  end

  # Only allow a list of trusted parameters through.
  def client_params # rubocop:disable Metrics/MethodLength
    params.require(:client).permit(
      :user_id,
      :first_name,
      :last_name,
      :nif,
      :street,
      :city,
      :region,
      :postal_code,
      :country,
      :email,
      :telephone,
      :active
    )
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<!-- Row -->
<tr id="<%= client.id %>">
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap w-px">
        <div class="flex items-center">
            <label class="inline-flex">
                <span class="sr-only">Select</span>
                <input class="table-item form-checkbox" type="checkbox" @click="uncheckParent" />
            </label>
        </div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
        <div class="flex items-center">
          <div class="font-medium text-slate-800"><%= client.full_name %></div>
        </div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
        <div class="text-left"><%= client.email %></div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
        <div class="text-left"><%= client.nif %></div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
        <div class="text-center font-medium text-emerald-500"><%= number_to_currency client.invoices.sum(:total) %></div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap w-px">
        <div class="space-x-1 inline-flex">
            <%= link_to edit_client_path(client), data: { turbo_frame: "modal" }, class: "text-slate-400 hover:text-slate-500" do %>
                <span class="sr-only"><%= t("editar") %></span>
                <svg class="w-8 h-8 fill-current" viewBox="0 0 32 32">
                    <path d="M19.7 8.3c-.4-.4-1-.4-1.4 0l-10 10c-.2.2-.3.4-.3.7v4c0 .6.4 1 1 1h4c.3 0 .5-.1.7-.3l10-10c.4-.4.4-1 0-1.4l-4-4zM12.6 22H10v-2.6l6-6 2.6 2.6-6 6zm7.4-7.4L17.4 12l1.6-1.6 2.6 2.6-1.6 1.6z" />
                </svg>
            <% end %>
            <%= button_to client_path(client), method: :delete, form: { data: { turbo_confirm: "¿Estás seguro?" } }, class: "text-rose-500 hover:text-rose-600" do %>
                <span class="sr-only"><%= t("eliminar") %></span>
                <svg class="w-8 h-8 fill-current" viewBox="0 0 32 32">
                    <path d="M13 15h2v6h-2zM17 15h2v6h-2z" />
                    <path d="M20 9c0-.6-.4-1-1-1h-6c-.6 0-1 .4-1 1v2H8v2h1v10c0 .6.4 1 1 1h12c.6 0 1-.4 1-1V13h1v-2h-4V9zm-6 1h4v1h-4v-1zm7 3v9H11v-9h10z" />
                </svg>
            <% end %>
        </div>
    </td>
</tr>

app/views/clients/_client.old.html.erb
<div id="<%= dom_id client %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= client.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= client.last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Nif:</strong>
    <%= client.nif %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Street:</strong>
    <%= client.street %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= client.city %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Region:</strong>
    <%= client.region %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Postal code:</strong>
    <%= client.postal_code %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Country:</strong>
    <%= client.country %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= client.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Telephone:</strong>
    <%= client.telephone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Active:</strong>
    <%= client.active %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this client", client, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this client', edit_client_path(client), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/clients/_form.html.erb
<div class="my-8 px-8 py-4 bg-white shadow-lg rounded-sm border border-slate-200"
data-controller="select" data-select-url-value="<%= regions_path %>" data-select-param-value="country">
  <%= form_with(model: client, class: "grid grid-cols-1 gap-y-6 sm:grid-cols-3 sm:gap-x-8") do |form| %>

    <div class="my-1">
      <%= form.label :first_name, t("nombres"), class: "input-label" %>
      <%= form.text_field :first_name, class: "form-input w-full" %>
    </div>

    <div class="my-1">
      <%= form.label :last_name, t("apellidos"), class: "input-label" %>
      <%= form.text_field :last_name, class: "form-input w-full" %>
    </div>

    <div class="my-1">
      <%= form.label :nif, t("nif"), class: "input-label" %>
      <%= form.text_field :nif, class: "form-input w-full" %>
    </div>

    <div class="my-1 col-span-2">
      <%= form.label :email, t("email"), class: "input-label" %>
      <%= form.text_field :email, class: "form-input w-full" %>
    </div>

    <div class="my-1">
      <%= form.label :telephone, t("telefono"), class: "input-label" %>
      <%= form.text_field :telephone, class: "form-input w-full" %>
    </div>

    <div class="my-1 sm:col-span-2">
      <%= form.label :street, t("calle"), class: "input-label" %>
      <%= form.text_field :street, class: "form-input w-full" %>
    </div>

    <div class="my-1">
      <%= form.label :city, t("ciudad"), class: "input-label" %>
      <%= form.text_field :city, class: "form-input w-full" %>
    </div>

    <div class="my-1">
      <%= form.label :country, t("pais"), class: "input-label" %>
      <%= form.collection_select :country, Country.all.sort, :alpha_2_code, :name,
        { selected: client.country_code}, { data: {action: "change->select#change"}, class: "form-input w-full"} %>
    </div>

    <div class="my-1">
      <%= form.label :region, t("provincia"), class: "input-label" %>
      <%= form.select :region, [(options_for_select client.get_regions, client.region)], {prompt: t("selecciona_provincia")}, { data: { select_target: "select" }, class: "form-input w-full"} %>
    </div>
    
    <div class="my-1">
      <%= form.label :postal_code, t("codigo_postal"), class: "input-label" %>
      <%= form.text_field :postal_code, class: "form-input w-full" %>
    </div>

    <div class="col-span-3">
    <% unless client.new_record? %>
      <div class="relative flex items-start my-1">
        <div class="flex h-5 items-center">
          <%= form.check_box :active, checked: true, class: "form-input p-2" %>
        </div>
        <div class="ml-3 text-sm">
          <%= form.label :active, t("activo"), class: "input-label" %>
        </div>
      </div>
    <% end %>
    </div>

    <div class="my-1 flex items-center justify-between col-span-3">
      <%= form.submit class: "btn btn-primary" %>
      <%= button_tag t("cancel"), data: { action: "modal#close" }, type: "button", class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/clients/create.turbo_stream.erb
<%= turbo_stream.prepend "clients", @client %>
<%= render_turbo_stream_flash_messages %>

app/views/clients/edit.html.erb
<div class="mx-auto md:w-3/4 w-full">
  <%= link_to sanitize("&larr; Regresar a clientes"), clients_path, class: "back-button" %>
  <!-- Turbo frame tag to render form -->
  <%= turbo_frame_tag "modal" do %>
    <h1 class="title"><%= t("editar_cliente") %> ✨</h1>
    <%= render "form", client: @client %>
  <% end %>
</div>

app/views/clients/index.html.erb
<% content_for(:html_title) { 'clientes' } %>
<!-- Page header -->
<div class="sm:flex sm:justify-between sm:items-center mb-8">

    <!-- Left: Title -->
    <div class="mb-4 sm:mb-0">
        <h1 class="text-2xl md:text-3xl text-slate-800 font-bold"><%= t("clientes") %> ✨</h1>
    </div>

    <!-- Right: Actions -->
    <div class="grid grid-flow-col sm:auto-cols-max justify-start sm:justify-end gap-2">

        <!-- Delete button -->
        <div class="table-items-action hidden">
            <div class="flex items-center">
                <div class="hidden xl:block text-sm italic mr-2 whitespace-nowrap">
                    <span class="table-items-count"></span> <%= t("clientes_selecionados") %>
                </div>
                <button class="btn bg-white border-slate-200 hover:border-slate-300 text-rose-500 hover:text-rose-600"><%= t("borrar") %></button>
            </div>
        </div>
        <% unless @clients.none? %>
            <!-- Sort and Search -->
            <div class="relative">
                <!-- Search form -->
                <%= form_with url: "", method: :get, data: { turbo_frame: "clients", turbo_action: "advance" } do |form| %>
                    <label for="action-search" class="sr-only"><%= t("buscar") %></label>
                    <%= form.search_field :query, value: params[:query], oninput: "this.form.requestSubmit()", class: "form-input pl-9 focus:border-slate-300", placeholder: t("buscar_clientes...") %>
                    <button class="absolute inset-0 right-auto group" type="submit" aria-label="Search">
                        <svg class="w-4 h-4 shrink-0 fill-current text-slate-500 group-hover:text-slate-500 ml-3 mr-2" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
                            <path d="M7 14c-3.86 0-7-3.14-7-7s3.14-7 7-7 7 3.14 7 7-3.14 7-7 7zM7 2C4.243 2 2 4.243 2 7s2.243 5 5 5 5-2.243 5-5-2.243-5-5-5z" />
                            <path d="M15.707 14.293L13.314 11.9a8.019 8.019 0 01-1.414 1.414l2.393 2.393a.997.997 0 001.414 0 .999.999 0 000-1.414z" />
                        </svg>
                    </button>

                    <label for="action-search" class="sr-only"><%= t("cantidad_por_pagina") %></label>
                    <%= form.select :count, options_for_select([10, 25, 50, 100], selected: params[:count]), {}, {class: "form-input pr-7 focus:border-slate-300 text-slate-500", onchange: "this.form.requestSubmit()"} %>

                <% end %>

            </div>
        <% end %>
        <!-- Add client button -->
        <%= button_to new_client_path, method: :get, class: "btn btn-primary", data: { turbo_frame: "modal" } do %>
            <svg class="w-4 h-4 fill-current opacity-50 shrink-0" viewBox="0 0 16 16">
                <path d="M15 7H9V1c0-.6-.4-1-1-1S7 .4 7 1v6H1c-.6 0-1 .4-1 1s.4 1 1 1h6v6c0 .6.4 1 1 1s1-.4 1-1V9h6c.6 0 1-.4 1-1s-.4-1-1-1z" />
            </svg>
            <span class="xs:block ml-2"> <%= t("nuevo_cliente") %> </span>
        <% end %>
    </div>

</div>
<!-- Table -->
<div class="bg-white shadow-lg rounded-sm border border-slate-200">
    <div x-data="handleSelect">

        <!-- Table -->
        <div class="overflow-x-auto">
            <% if @clients.none? %>
                <% if params[:query].nil? %>
                    <%= render "shared/empty_state", title: t("no_hay_clientes"), text: t("no_hay_clientes_texto"), button_text: t("nuevo_cliente"), the_link: new_client_path %>
                <% else %>
                    <%= render "shared/search_not_found", the_link: clients_url %>
                <% end %>
            <% else %>
                <table class="table-auto w-full">
                    <!-- Table header -->
                    <thead class="text-xs font-semibold uppercase text-slate-500 bg-slate-50 border-t border-b border-slate-200">
                        <tr>
                            <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap w-px">
                                <div class="flex items-center">
                                    <label class="inline-flex">
                                        <span class="sr-only"><%=t("seleccionar_todo")%></span>
                                        <input id="parent-checkbox" class="form-checkbox" type="checkbox" @click="toggleAll" />
                                    </label>
                                </div>
                            </th>
                            <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                                <div class="font-semibold text-left relative <%= "text-indigo-500" if params[:sort] == "name" %>">
                                    <%= sort_link_to t("nombre"), :name, data: { turbo_action: "advance" } %>
                                    <span class="absolute top-0 left-13">
                                        <%= sort_indicator if params[:sort] == "name" %>
                                    </span>
                                </div>
                            </th>
                            <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                                <div class="font-semibold text-left relative <%= "text-indigo-500" if params[:sort] == "email" %>">
                                    <%= sort_link_to t("email"), :email, data: { turbo_action: "advance" } %>
                                    <span class="absolute top-0 left-18">
                                        <%= sort_indicator if params[:sort] == "email" %>
                                    </span>
                                </div>
                            </th>
                            <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                                <div class="font-semibold text-left relative <%= "text-indigo-500" if params[:sort] == "nif" %>">
                                    <%= sort_link_to t("nif"), :nif, data: { turbo_action: "advance" } %>
                                    <span class="absolute top-0 left-5">
                                        <%= sort_indicator if params[:sort] == "nif" %>
                                    </span>
                                </div>
                            </th>
                            <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                                <div class="font-semibold text-center">
                                    <%=t("total_facturado")%>
                                </div>
                            </th>
                            <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                                <span class="sr-only"><%=t("acciones")%></span>
                            </th>
                        </tr>
                    </thead>
                    <!-- Table body, with id clients for turbo frame -->
                    <tbody id="clients" class="text-sm divide-y divide-slate-200">
                        <!-- Rows -->
                        <%= render @clients %>
                    </tbody>
                </table>
            <% end %>
        </div>
    </div>
</div>
<!-- Pagination -->
<% unless @clients.none? %>
    <%= render "shared/pagination", item_name: t('cliente') %>
<% end %>

<script>
    // A basic demo function to handle "select all" functionality
    document.addEventListener('alpine:init', () => {
        Alpine.data('handleSelect', () => ({
            selectall: false,
            selectAction() {
                countEl = document.querySelector('.table-items-action');
                if (!countEl) return;
                checkboxes = document.querySelectorAll('input.table-item:checked');
                document.querySelector('.table-items-count').innerHTML = checkboxes.length;
                if (checkboxes.length > 0) {
                    countEl.classList.remove('hidden');
                } else {
                    countEl.classList.add('hidden');
                }
            },
            toggleAll() {
                this.selectall = !this.selectall;
                checkboxes = document.querySelectorAll('input.table-item');
                [...checkboxes].map((el) => {
                    el.checked = this.selectall;
                });
                this.selectAction();
            },
            uncheckParent() {
                this.selectall = false;
                document.getElementById('parent-checkbox').checked = false;
                this.selectAction();
            }
        }))
    })    
</script>

app/views/clients/index.old.html.erb
<% content_for(:html_title) { 'Clientes' } %>
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h2 class="font-bold text-xl">Lista de clientes</h2>
    <%= link_to 'Nuevo cliente', new_client_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="clients" class="min-w-full">
    <%= render @clients %>
  </div>
</div>

app/views/clients/new.html.erb
<div class="mx-auto md:w-3/4 w-full">
  <%= link_to sanitize("&larr; Regresar a clientes"), clients_path, class: "back-button" %>
  <!-- Turbo frame tag to render form -->
  <%= turbo_frame_tag "modal" do %>
    <h1 class="title"><%= t("nuevo_cliente") %> ✨</h1>
    <%= render "form", client: @client %>
  <% end %>
</div>

app/views/clients/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @client %>

    <%= link_to 'Edit this client', edit_client_path(@client), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this client', client_path(@client), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to clients', clients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/clients/show.turbo_stream.erb
<%= turbo_stream.replace target="client_details" do %>
    <div class="col-span-2 mb-10">
        <div id="client_details" class="p-2 border form-input bg-slate-50" data-clientselect-target="select">
            <div class="flex justify-between items-center">
                <h3 class="input-label underline" for="client_details"><%= t("detalle_cliente") %></h3>
                  <%= link_to edit_client_path(@client), data: { turbo_frame: "modal" }, class: "text-indigo-600 hover:underline" do %>
                  <span class="sr-only"><%= t("editar") %></span>
                  <%= (heroicon "pencil-square", options: { class: "inline"} ) %>
                <% end %>
            </div>
            <p>NIF/CIF: <%= @client.nif %></p>
            <p><%= @client.address_line1 %></p>
            <p><%= @client.address_line2 %></p>
        </div>
    </div>
<% end %>

app/views/clients/update.turbo_stream.erb
<%= turbo_stream.replace @client.id, @client %>
<%= render_turbo_stream_flash_messages %>