config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # root 'home#index', as: 'home_index', via: :all
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
  resources :clients
  resources :items
  resources :invoices do
    resources :line_items, except: [:index]
    post :add_item, on: :collection
  end
  resources :after_register

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/regions', to: 'countries#regions'
  get '/dashboard', to: 'dashboard#index'
  get 'charts/show', as: :chart

  # scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
  #   resources :users
  #   resources :dashboard
  #   resources :invoices
  #   resources :clients
  #   resources :items
  # end

  # localized do
  #   resources :users
  #   # get '/users/edit', to: 'registrations#edit', as: :edit_user_registration
  #   get '/invoices', to: 'invoices#index', as: :invoices
  #   get '/invoices/new', to: 'invoices#new', as: :new_invoice
  #   get '/invoices/:id', to: 'invoices#show', as: :show_invoice
  #   get '/invoices/edit/:id', to: 'invoices#edit', as: :edit_invoice
  #   get '/clients', to: 'clients#index', as: :clients
  #   get '/clients/new', to: 'clients#new', as: :new_client
  #   get '/clients/:id', to: 'clients#show', as: :show_client
  #   get '/clients/edit/:id', to: 'clients#edit', as: :edit_client
  #   get '/items', to: 'items#index', as: :items
  #   get '/items/new', to: 'items#new', as: :new_item
  #   get '/items/:id', to: 'items#show', as: :show_item
  #   get '/items/edit/:id', to: 'items#edit', as: :edit_item
  #   get '/dashboard', to: 'dashboard#index', as: :dashboard
  #   get '/privacy', to: 'home#privacy', as: :privacy
  # end

  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :user
  has_many :line_items
  has_many :invoices, through: :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :item_name, :price, :iva, presence: true
  validates :item_name, uniqueness: true, length: { maximum: 100 }
  validates :description, length: { maximum: 300 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :iva, numericality: { greater_than_or_equal_to: 0 }

  pg_search_scope :search,
                  against: %i[item_name description price iva],
                  using: { tsearch: { prefix: true } },
                  ignoring: :accents

  private

  # ensure that there are no line items referencing this item
  def ensure_not_referenced_by_any_line_item
    return if line_items.empty?

    errors.add(:base, 'Ítem presente en una Factura')
    throw :abort
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: %i[show edit update destroy]

  # GET /items or /items.json
  def index
    @items = current_user.items
    @items = current_user.items.search(params[:query]) if params[:query].present?
    @pagy, @items = pagy @items.reorder(sort_column => sort_direction), items: params.fetch(:count, 10)
  end

  def sort_column
    %w[item_name description price iva].include?(params[:sort]) ? params[:sort] : 'item_name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  # GET /items/1 or /items/1.json
  def show
    @target = params[:target]
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit; end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    @item.user = current_user

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, notice: I18n.t('item_creado') }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_path, notice: I18n.t('item_actualizado') }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    if @item.destroy
      respond_to do |format|
        format.html { redirect_to items_path, notice: I18n.t('item_borrado') }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to items_path, notice: I18n.t('item_fallo_borrar'), status: :unprocessable_entity }
        format.json { render json: { error: @item.errors.full_messages.join('. ') }, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(
      :user_id,
      :item_name,
      :description,
      :price,
      :iva
    )
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="my-8 px-8 py-4 bg-white shadow-lg rounded-sm border border-slate-200">
  <%= form_with(model: item, class: "grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8") do |form| %>

    <div class="my-1 sm:col-span-2">
      <%= form.label :item_name, t("nombre"), class: "input-label" %>
      <%= form.text_field :item_name, class: "form-input w-full", autofocus: true %>
    </div>

    <div class="my-1 sm:col-span-2">
      <%= form.label :descripticon, t("descripcion"), class: "input-label" %>
      <%= form.text_area :description, rows: 10, cols: 60, class: "form-input w-full" %>
    </div>

    <div class="my-1">
      <%= form.label :price, t("precio"), class: "input-label" %>
      <%= form.text_field :price, class: "form-input w-full" %>
    </div>

    <div class="my-1">
      <%= form.label :iva, t("iva"), class: "input-label" %>
      <%= form.select :iva, options_for_select([["21%", 21], ["10%", 10], ["4%", 4], ["0%", 0]]), {}, {class: "form-select w-full" } %>
    </div>

    <div class="my-1 flex items-center justify-between col-span-2">
      <%= form.submit class: "btn btn-primary" %>
      <%= button_tag t("cancel"), data: { action: "modal#close" }, type: "button", class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/items/_item.html copy.erb
<!-- Row -->
<tr>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap w-px">
        <div class="flex items-center">
            <label class="inline-flex">
                <span class="sr-only">Select</span>
                <input class="table-item form-checkbox" type="checkbox" @click="uncheckParent" />
            </label>
        </div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 break-words">
        <div class="flex items-center">
          <div class="font-medium text-slate-800"><%= item.item_name %></div>
        </div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 break-words">
        <div class="text-left"><%= item.description %></div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
        <div class="text-left"><%= number_to_currency(item.price, locale: :es) %></div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
        <div class="text-center"><%= item.iva %></div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
        <div class="text-center"><%= item.irpf %></div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap w-px">
        <%= link_to "Editar",
                    edit_item_path(item),
                    class: "link" %>
        <%= button_to "Borrar",
                    item_path(item),
                    method: :delete,
                    class: "link" %>
    </td>
</tr>

app/views/items/_item.html.erb
<!-- Row -->
<tr id="<%= item.id %>">
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap w-px">
        <div class="flex items-center">
            <label class="inline-flex">
                <span class="sr-only">Select</span>
                <input class="table-item form-checkbox" type="checkbox" @click="uncheckParent" />
            </label>
        </div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 break-words">
        <div class="flex items-center">
            <%= link_to item.item_name, item, data: { turbo_frame: "_top" }, class: "font-medium text-slate-800" %>
        </div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 break-words">
        <div class="text-left"><%= simple_format item.description %></div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
        <div class="text-left"><%= number_to_currency(item.price, locale: :es) %></div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
        <div class="text-center"><%= item.iva %></div>
    </td>
    <td class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap w-px">
        <div class="space-x-1 inline-flex">
            <%= link_to edit_item_path(item), data: { turbo_frame: "_top" }, class: "text-slate-400 hover:text-slate-500" do %>
                <span class="sr-only"><%= t("editar_item") %></span>
                <svg class="w-8 h-8 fill-current" viewBox="0 0 32 32">
                    <path d="M19.7 8.3c-.4-.4-1-.4-1.4 0l-10 10c-.2.2-.3.4-.3.7v4c0 .6.4 1 1 1h4c.3 0 .5-.1.7-.3l10-10c.4-.4.4-1 0-1.4l-4-4zM12.6 22H10v-2.6l6-6 2.6 2.6-6 6zm7.4-7.4L17.4 12l1.6-1.6 2.6 2.6-1.6 1.6z" />
                </svg>
            <% end %>
            <%= button_to item_path(item), method: :delete, form: { data: { turbo_confirm: t("estas_seguro") } }, class: "text-rose-500 hover:text-rose-600" do %>
                <span class="sr-only"><%= t("borrar_item") %></span>
                <svg class="w-8 h-8 fill-current" viewBox="0 0 32 32">
                    <path d="M13 15h2v6h-2zM17 15h2v6h-2z" />
                    <path d="M20 9c0-.6-.4-1-1-1h-6c-.6 0-1 .4-1 1v2H8v2h1v10c0 .6.4 1 1 1h12c.6 0 1-.4 1-1V13h1v-2h-4V9zm-6 1h4v1h-4v-1zm7 3v9H11v-9h10z" />
                </svg>
            <% end %>
        </div>
    </td>
</tr>

app/views/items/_item.html.old.erb
<div class="mt-2" id="<%= dom_id item %>">
  <p>
    <strong>Title:</strong>
    <%= item.item_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= item.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= item.price %>
  </p>

  <p>
    <strong>IVA:</strong>
    <%= item.iva %>
  </p>

  <p>
    <strong>IRPF:</strong>
    <%= item.irpf %>
  </p>

</div>

app/views/items/create.turbo_stream.erb
<%= turbo_stream.prepend 'items', @item %>
<%= render_turbo_stream_flash_messages %>

app/views/items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= link_to sanitize(t("regresar_a_items")), items_path, class: "back-button" %>
  <h1 class="title"><%= t("editar_item") %> ✨</h1>

  <%= render "form", item: @item %>
  
</div>

app/views/items/index.html.erb
<% content_for(:html_title) { 'items' } %>
<!-- Page header -->
<div class="sm:flex sm:justify-between sm:items-center mb-8">

    <!-- Left: Title -->
    <div class="mb-4 sm:mb-0">
        <h1 class="text-2xl md:text-3xl text-slate-800 font-bold"><%= t("items") %> ✨</h1>
    </div>

    <!-- Right: Actions -->
    <div class="grid grid-flow-col sm:auto-cols-max justify-start sm:justify-end gap-2">

        <!-- Delete button -->
        <div class="table-items-action hidden">
            <div class="flex items-center">
                <div class="hidden xl:block text-sm italic mr-2 whitespace-nowrap"><span class="table-items-count"></span> <%= t("items_selecionados") %></div>
                <button class="btn bg-white border-slate-200 hover:border-slate-300 text-rose-500 hover:text-rose-600"><%= t("borrar") %></button>
            </div>
        </div>
        <!-- Sort and Search -->
        <% unless @items.none? %>
            <div class="relative">
                <%= form_with url: "", method: :get, data: { turbo_frame: "items", turbo_action: "advance" } do |form| %>
                    <!-- Search form -->
                    <label for="action-search" class="sr-only"><%= t("buscar") %></label>
                    <%= form.search_field :query, value: params[:query], oninput: "this.form.requestSubmit()", class: "form-input pl-9 focus:border-slate-300", placeholder: t("buscar_items") %>
                    <button class="absolute inset-0 right-auto group" type="submit" aria-label="Search">
                        <svg class="w-4 h-4 shrink-0 fill-current text-slate-500 group-hover:text-slate-500 ml-3 mr-2" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
                            <path d="M7 14c-3.86 0-7-3.14-7-7s3.14-7 7-7 7 3.14 7 7-3.14 7-7 7zM7 2C4.243 2 2 4.243 2 7s2.243 5 5 5 5-2.243 5-5-2.243-5-5-5z" />
                            <path d="M15.707 14.293L13.314 11.9a8.019 8.019 0 01-1.414 1.414l2.393 2.393a.997.997 0 001.414 0 .999.999 0 000-1.414z" />
                        </svg>
                    </button>
                    <!-- Sort --> 
                    <label for="action-search" class="sr-only"><%= t("cantidad_por_pagina") %></label>
                    <%= form.select :count, options_for_select([10, 25, 50, 100], selected: params[:count]), {}, {class: "form-input pr-7 focus:border-slate-300 text-slate-500", onchange: "this.form.requestSubmit()"} %>
                <% end %>
            </div>
        <% end %>
        <!-- Add item button -->
        <%= button_to new_item_path, method: :get, class: "btn btn-primary", data: { turbo_frame: "_top" } do %>
            <svg class="w-4 h-4 fill-current opacity-50 shrink-0" viewBox="0 0 16 16">
                <path d="M15 7H9V1c0-.6-.4-1-1-1S7 .4 7 1v6H1c-.6 0-1 .4-1 1s.4 1 1 1h6v6c0 .6.4 1 1 1s1-.4 1-1V9h6c.6 0 1-.4 1-1s-.4-1-1-1z" />
            </svg>
            <span class="xs:block ml-2"><%= t("nuevo_item") %></span>
        <% end %>                            
        
    </div>

</div>
<%= turbo_frame_tag "items" do %>
    <!-- Table -->
    <div class="bg-white shadow-lg rounded-sm border border-slate-200">
        <div x-data="handleSelect">
            <!-- Table -->
            <div class="overflow-x-auto">
                <% if @items.none? %>
                    <% if params[:query].nil? %>
                        <%= render "shared/empty_state", title: t("no_hay_items"), text: t("no_hay_items_texto"), button_text: t("nuevo_item"), the_link: new_item_path %>
                    <% else %>
                        <%= render "shared/search_not_found", the_link: items_url %>
                    <% end %>
                <% else %>
                    <table class="table-auto w-full">
                        <!-- Table header -->
                        <thead class="text-xs font-semibold uppercase text-slate-500 bg-slate-50 border-t border-b border-slate-200">
                            <tr>
                                <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap w-px">
                                    <div class="flex items-center">
                                        <label class="inline-flex">
                                            <span class="sr-only"><%= t("seleccionar_todo") %></span>
                                            <input id="parent-checkbox" class="form-checkbox" type="checkbox" @click="toggleAll" />
                                        </label>
                                    </div>
                                </th>
                                <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                                    <div class="font-semibold text-left relative <%= "text-indigo-500" if params[:sort] == "item_name" %>">
                                        <%= sort_link_to t("nombre"), :item_name, data: { turbo_action: "advance" } %>
                                        <span class="absolute top-0 left-14">
                                            <%= sort_indicator if params[:sort] == "item_name" %>
                                        </span>
                                    </div>
                                </th>
                                <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                                    <div class="font-semibold text-left relative <%= "text-indigo-500" if params[:sort] == "description" %>">
                                        <%= sort_link_to t("descripcion"), :description, data: { turbo_action: "advance" } %>
                                        <span class="absolute top-0 left-15 text-indigo-500">
                                            <%= sort_indicator if params[:sort] == "description" %>
                                        </span>
                                    </div>
                                </th>
                                <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                                    <div class="font-semibold text-left relative <%= "text-indigo-500" if params[:sort] == "price" %>">
                                        <%= sort_link_to t("precio"), :price, data: { turbo_action: "advance" } %>
                                        <span class="absolute top-0 left-13 text-indigo-500">
                                            <%= sort_indicator if params[:sort] == "price" %>
                                        </span>
                                    </div>
                                </th>
                                <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                                    <div class="font-semibold relative <%= "text-indigo-500" if params[:sort] == "iva" %>">
                                        <%= sort_link_to t("iva") , :iva, data: { turbo_action: "advance" } %>
                                        <span class="absolute top-0 left-5 text-indigo-500">
                                            <%= sort_indicator if params[:sort] == "iva" %>
                                        </span>
                                    </div>
                                </th>
                                <th class="px-2 first:pl-5 last:pr-5 py-3 whitespace-nowrap">
                                    <span class="sr-only"><%= t("acciones") %></span>
                                </th>
                            </tr>
                        </thead>
                        <!-- Table body -->
                        <tbody class="text-sm divide-y divide-slate-200">
                        <!-- Rows -->
                        <%= render @items %>
                        </tbody>
                    </table>
                <% end %>
            </div>
        </div>
    </div>
    <!-- Pagination -->
    <% unless @items.none? %>
        <%= render "shared/pagination", item_name: t('item') %>
    <% end %>
<% end %>
<script>
    // A basic demo function to handle "select all" functionality
    document.addEventListener('alpine:init', () => {
        Alpine.data('handleSelect', () => ({
            selectall: false,
            selectAction() {
                countEl = document.querySelector('.table-items-action');
                if (!countEl) return;
                checkboxes = document.querySelectorAll('input.table-item:checked');
                document.querySelector('.table-items-count').innerHTML = checkboxes.length;
                if (checkboxes.length > 0) {
                    countEl.classList.remove('hidden');
                } else {
                    countEl.classList.add('hidden');
                }
            },
            toggleAll() {
                this.selectall = !this.selectall;
                checkboxes = document.querySelectorAll('input.table-item');
                [...checkboxes].map((el) => {
                    el.checked = this.selectall;
                });
                this.selectAction();
            },
            uncheckParent() {
                this.selectall = false;
                document.getElementById('parent-checkbox').checked = false;
                this.selectAction();
            }
        }))
    })    
</script>

app/views/items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
    <%= link_to sanitize(t("regresar_a_items")), items_path, class: "back-button" %>

      <h1 class="title"><%= t("nuevo_item") %> ✨</h1>
      <%= render "form", item: @item %>
</div>

app/views/items/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
<%= link_to sanitize(t("regresar_a_items")), items_path, class: "back-button" %>
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="notice" id="notice"><%= notice %></p>
    <% end %>

    <h1 class="title"><%= @item.item_name %></h1>
    <p><%= simple_format @item.description %></p>
    <div class="flex justify-between items-center">
      <div class="flex gap-2">
        <%= t("iva") %>:
        <span class="font-normal"><%= @item.iva %></span>
      </div>
      <div class="flex gap-2">
        <%= t("precio") %>:
        <span class="font-semibold"><%= number_to_currency(@item.price, locale: :es) %></span>
      </div>
    </div>
  </div>
</div>

app/views/items/show.turbo_stream.erb
<%= turbo_stream.replace target="invoice_line_items_attributes_#{@target}_price" do %>
    <input class="form-input w-full" readonly data-recalculate-target="price" data-itemselect-target="select" type="text" name="invoice[line_items_attributes][<%=@target%>][price]" id="invoice_line_items_attributes_<%=@target%>_price" value="<%= @item&.price %>">
<% end %>

<%= turbo_stream.replace target="invoice_line_items_attributes_#{@target}_iva" do %>
    <input class="form-input w-full" readonly data-recalculate-target="iva" type="text" name="invoice[line_items_attributes][<%=@target%>][iva]" id="invoice_line_items_attributes_<%=@target%>_iva" value="<%= @item&.iva %>">
<% end %>

<%= turbo_stream.replace target="invoice_line_items_attributes_#{@target}_quantity" do %>
    <input min="0" max="10000000" step=1 class="form-input w-full" data-action="change->recalculate#recalculate" data-removeitem-target="qty" data-recalculate-target="qty"
    type="number" name="invoice[line_items_attributes][<%=@target%>][quantity]" id="invoice_line_items_attributes_<%=@target%>_quantity" value="0">
<% end %>